language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
before_script:
  - "bundle exec rake test:setup"
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/railsedge.gemfile
